title: 끄적이는 개발일지
description: 파이썬, JAVA등 다양한 개발을 공부하는 블로그

url:   https://kcy51156.github.io
image: /images/logo.png

show_downloads: false
future:         true
# timezone:       Asia/Seoul
cayman-blog:
  date_format: "%b %-d, %Y"

theme: 

permalink: /:categories/:title

# social
author: Chanyang Kim
disqus_shortname:   kcy51156
google_analytics:   UA-111508093-1

repository: kcy51156/kcy51156.github.io

highlighter: rouge
markdown:    kramdown
lsi: false
excerpt_separator: "\n\n"
incremental: false

# root_dir: http://localhost:4000
category_dir: categories/
tag_dir: tag/
categories: [android, aws, data_science, git, jekyll, linux, machine-learning, python, pytorch, review, synology, thoughts]

paginate: 10
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

